import React from 'react'
import bg from "../Photos/BG.png"

function FlightRules() {
    return (
        <div className=' mt-3 w-full border'>
            <div className=' w-full py-2 px-2 border-b flex items-center' >
                <img src={bg} alt="" className=' w-8 mr-2' />
                <p className=' font-medium'>Dhaka to Chittagong <span className=' font-normal'>and</span> Chittagong to Dhaka</p>
            </div>
            <div className=' p-5 h-72 overflow-y-scroll border-b'>
                <p className=' bg-[#ffedd1] p-3 text-[11px] rounded'><span className=' font-medium'>*Note For Voluntary Cancellation:</span>Service fees & gateway charges will be additionally applied on top of penalty amount. Some taxes may not be refundable</p>
                <p className=' bg-[#ffedd1] my-3 p-3 text-[11px] rounded'><span className=' font-medium mt-3'>*Note For Date Change:</span>Service Fees, Fare difference and Tax difference will be additionally applied on top of penalty amount which is nonrefundable in any circumstances.</p>

                <p className=' text-2xl mb-2'>Segment 1</p>
                <p className=' text-sm sm:text-base'>
                    VOLUNTARY CHANGES
                    DO A CATEGORY 31 SPECIFIC TEXT ENTRY TO VIEW CONTENTS
                    ALSO REFERENCE 16 PENALTIES - FOR ADDITIONAL CHANGE INFORMATION
                    VOLUNTARY REFUNDS
                    UNLESS OTHERWISE SPECIFIED
                    APPLIES IN THE CASE OF DEATH OF PASSENGER OR FAMILY
                    MEMBER.
                    NO CHARGE. IF ALL PENALTIES IN PRICING UNIT ARE PER
                    PRICING UNIT COLLECT HIGHEST. IF MIX OF PER FARE
                    COMPONENT AND PER PRICING UNIT CALCULATE EACH AS PER
                    PRICING UNIT AND COLLECT HIGHEST.
                    REFUND REQUEST MUST BE WITHIN 6 MONTHS AFTER TICKET
                    ISSUANCE. FORM OF REFUND - ORIGINAL FORM OF PAYMENT. ONLY
                    VALIDATING CARRIER MAY REFUND TICKET.
                    REPRICE FLOWN PORTION USING FARES IN EFFECT ON TICKET
                    ISSUANCE DATE. FOR FULLY FLOWN FARE COMPONENTS FARE BREAK
                    POINTS MAY NOT BE CHANGED. FOR PARTIALLY FLOWN FARE
                    COMPONENTS ONLY DESTINATION FARE BREAK POINTS MAY BE
                    CHANGED. REPRICE USING NORMAL/SPECIAL ONE WAY FARES/ANY
                    RULE/FARE CLASS/SAME RBD. PUBLIC FARES ARE USED IF
                    TICKETED FARE IS IN PUBLIC TARIFF. QUALIFIED PRIVATE
                    FARES OR PUBLIC FARES ARE USED IF TICKETED FARE IS IN
                    PRIVATE TARIFF. NEW FARE FOR FULLY FLOWN FARE COMPONENTS
                    MUST BE EQUAL TO OR HIGHER THAN TICKETED FARE.
                    FOR TICKETING ON/AFTER 01APR 20
                    VALID FOR INFANT WITHOUT A SEAT.
                    NO CHARGE. IF ALL PENALTIES IN PRICING UNIT ARE PER
                    PRICING UNIT COLLECT HIGHEST. IF MIX OF PER FARE
                    COMPONENT AND PER PRICING UNIT CALCULATE EACH AS PER
                    PRICING UNIT AND COLLECT HIGHEST.
                    REFUND REQUEST MUST BE WITHIN 6 MONTHS AFTER TICKET
                    ISSUANCE. FORM OF REFUND - ORIGINAL FORM OF PAYMENT.
                    ONLY VALIDATING CARRIER MAY REFUND TICKET.
                    REPRICE FLOWN PORTION USING FARES IN EFFECT ON TICKET
                    ISSUANCE DATE. FOR FULLY FLOWN FARE COMPONENTS FARE
                    BREAK POINTS MAY NOT BE CHANGED. FOR PARTIALLY FLOWN
                    FARE COMPONENTS ONLY DESTINATION FARE BREAK POINTS MAY
                    BE CHANGED. REPRICE USING NORMAL/SPECIAL ONE WAY/ROUND
                    TRIP FARES/ANY RULE/FARE CLASS/RBD. PUBLIC FARES ARE
                    USED IF TICKETED FARE IS IN PUBLIC TARIFF. QUALIFIED
                    PRIVATE FARES OR PUBLIC FARES ARE USED IF TICKETED FARE
                    IS IN PRIVATE TARIFF. NEW FARE FOR FULLY FLOWN FARE
                    COMPONENTS MUST BE EQUAL TO OR HIGHER THAN TICKETED
                    FARE.
                    FOR TICKETING ON/AFTER 01MAR 21
                    REFUND REQUEST REQUIRED 24 HOURS BEFORE ORIGINALLY
                    SCHEDULED FLIGHT OF FIRST UNUSED TICKET COUPON.
                    CHARGE BDT 1500 PER PRICING UNIT. IF ALL PENALTIES IN
                    PRICING UNIT ARE PER PRICING UNIT COLLECT HIGHEST. IF
                    MIX OF PER FARE COMPONENT AND PER PRICING UNIT
                    CALCULATE EACH AS PER PRICING UNIT AND COLLECT HIGHEST.
                    DISCOUNT APPLIES TO CHILD/INFANT.
                    REFUND REQUEST MUST BE WITHIN 6 MONTHS AFTER TICKET
                    ISSUANCE. FORM OF REFUND - ORIGINAL FORM OF PAYMENT.
                    ONLY VALIDATING CARRIER MAY REFUND TICKET.
                    REPRICE FLOWN PORTION USING FARES IN EFFECT ON TICKET
                    ISSUANCE DATE. FOR FULLY FLOWN FARE COMPONENTS FARE
                    BREAK POINTS MAY NOT BE CHANGED. FOR PARTIALLY FLOWN
                    FARE COMPONENTS ONLY DESTINATION FARE BREAK POINTS MAY
                    BE CHANGED. REPRICE USING NORMAL/SPECIAL ONE WAY/ROUND
                    TRIP FARES/ANY RULE/FARE CLASS/RBD. PUBLIC FARES ARE
                    USED IF TICKETED FARE IS IN PUBLIC TARIFF. QUALIFIED
                    PRIVATE FARES OR PUBLIC FARES ARE USED IF TICKETED FARE
                    IS IN PRIVATE TARIFF. NEW FARE FOR FULLY FLOWN FARE
                    COMPONENTS MUST BE EQUAL TO OR HIGHER THAN TICKETED
                    FARE.
                    FOR TICKETING ON/AFTER 01APR 20
                    REFUND REQUEST REQUIRED BEFORE ORIGINALLY SCHEDULED
                    FLIGHT OF FIRST UNUSED TICKET COUPON.
                    CHARGE BDT 2000 PER PRICING UNIT. IF ALL PENALTIES IN
                    PRICING UNIT ARE PER PRICING UNIT COLLECT HIGHEST. IF
                    MIX OF PER FARE COMPONENT AND PER PRICING UNIT
                    CALCULATE EACH AS PER PRICING UNIT AND COLLECT HIGHEST.
                    DISCOUNT APPLIES TO CHILD/INFANT.
                    REFUND REQUEST MUST BE WITHIN 6 MONTHS AFTER TICKET
                    ISSUANCE. FORM OF REFUND - ORIGINAL FORM OF PAYMENT.
                    ONLY VALIDATING CARRIER MAY REFUND TICKET.
                    REPRICE FLOWN PORTION USING FARES IN EFFECT ON TICKET
                    ISSUANCE DATE. FOR FULLY FLOWN FARE COMPONENTS FARE
                    BREAK POINTS MAY NOT BE CHANGED. FOR PARTIALLY FLOWN
                    FARE COMPONENTS ONLY DESTINATION FARE BREAK POINTS MAY
                    BE CHANGED. REPRICE USING NORMAL/SPECIAL ONE WAY/ROUND
                    TRIP FARES/ANY RULE/FARE CLASS/RBD. PUBLIC FARES ARE
                    USED IF TICKETED FARE IS IN PUBLIC TARIFF. QUALIFIED
                    PRIVATE FARES OR PUBLIC FARES ARE USED IF TICKETED FARE
                    IS IN PRIVATE TARIFF. NEW FARE FOR FULLY FLOWN FARE
                    COMPONENTS MUST BE EQUAL TO OR HIGHER THAN TICKETED
                    FARE.
                    OR -
                    REFUND REQUEST REQUIRED ANYTIME AFTER ORIGINALLY
                    SCHEDULED FLIGHT OF FIRST UNUSED TICKET COUPON.
                    CHARGE BDT 2000 PER PRICING UNIT. IF ALL PENALTIES
                    IN PRICING UNIT ARE PER PRICING UNIT COLLECT
                    HIGHEST. IF MIX OF PER FARE COMPONENT AND PER
                    PRICING UNIT CALCULATE EACH AS PER PRICING UNIT
                    AND COLLECT HIGHEST. DISCOUNT APPLIES TO CHILD/
                    INFANT.
                    REFUND REQUEST MUST BE WITHIN 6 MONTHS AFTER TICKET
                    ISSUANCE. FORM OF REFUND - ORIGINAL FORM OF
                    PAYMENT. ONLY VALIDATING CARRIER MAY REFUND
                    TICKET.
                    REPRICE FLOWN PORTION USING FARES IN EFFECT ON
                    TICKET ISSUANCE DATE. FOR FULLY FLOWN FARE
                    COMPONENTS FARE BREAK POINTS MAY NOT BE CHANGED.
                    FOR PARTIALLY FLOWN FARE COMPONENTS ONLY
                    DESTINATION FARE BREAK POINTS MAY BE CHANGED.
                    REPRICE USING NORMAL/SPECIAL ONE WAY/ROUND TRIP
                    FARES/ANY RULE/FARE CLASS/RBD. PUBLIC FARES ARE
                    USED IF TICKETED FARE IS IN PUBLIC TARIFF.
                    QUALIFIED PRIVATE FARES OR PUBLIC FARES ARE USED
                    IF TICKETED FARE IS IN PRIVATE TARIFF. NEW FARE
                    FOR FULLY FLOWN FARE COMPONENTS MUST BE EQUAL TO
                    OR HIGHER THAN TICKETED FARE.


                    VOLUNTARY CHANGES
                    DO A CATEGORY 31 SPECIFIC TEXT ENTRY TO VIEW CONTENTS
                    ALSO REFERENCE 16 PENALTIES - FOR ADDITIONAL CHANGE INFORMATION


                    VOLUNTARY REFUNDS
                    UNLESS OTHERWISE SPECIFIED
                    APPLIES IN THE CASE OF DEATH OF PASSENGER OR FAMILY
                    MEMBER.
                    NO CHARGE. IF ALL PENALTIES IN PRICING UNIT ARE PER
                    PRICING UNIT COLLECT HIGHEST. IF MIX OF PER FARE
                    COMPONENT AND PER PRICING UNIT CALCULATE EACH AS PER
                    PRICING UNIT AND COLLECT HIGHEST.
                    REFUND REQUEST MUST BE WITHIN 6 MONTHS AFTER TICKET
                    ISSUANCE. FORM OF REFUND - ORIGINAL FORM OF PAYMENT. ONLY
                    VALIDATING CARRIER MAY REFUND TICKET.
                    REPRICE FLOWN PORTION USING FARES IN EFFECT ON TICKET
                    ISSUANCE DATE. FOR FULLY FLOWN FARE COMPONENTS FARE BREAK
                    POINTS MAY NOT BE CHANGED. FOR PARTIALLY FLOWN FARE
                    COMPONENTS ONLY DESTINATION FARE BREAK POINTS MAY BE
                    CHANGED. REPRICE USING NORMAL/SPECIAL ONE WAY FARES/ANY
                    RULE/FARE CLASS/SAME RBD. PUBLIC FARES ARE USED IF
                    TICKETED FARE IS IN PUBLIC TARIFF. QUALIFIED PRIVATE
                    FARES OR PUBLIC FARES ARE USED IF TICKETED FARE IS IN
                    PRIVATE TARIFF. NEW FARE FOR FULLY FLOWN FARE COMPONENTS
                    MUST BE EQUAL TO OR HIGHER THAN TICKETED FARE.
                    FOR TICKETING ON/AFTER 01APR 20
                    VALID FOR INFANT WITHOUT A SEAT.
                    NO CHARGE. IF ALL PENALTIES IN PRICING UNIT ARE PER
                    PRICING UNIT COLLECT HIGHEST. IF MIX OF PER FARE
                    COMPONENT AND PER PRICING UNIT CALCULATE EACH AS PER
                    PRICING UNIT AND COLLECT HIGHEST.
                    REFUND REQUEST MUST BE WITHIN 6 MONTHS AFTER TICKET
                    ISSUANCE. FORM OF REFUND - ORIGINAL FORM OF PAYMENT.
                    ONLY VALIDATING CARRIER MAY REFUND TICKET.
                    REPRICE FLOWN PORTION USING FARES IN EFFECT ON TICKET
                    ISSUANCE DATE. FOR FULLY FLOWN FARE COMPONENTS FARE
                    BREAK POINTS MAY NOT BE CHANGED. FOR PARTIALLY FLOWN
                    FARE COMPONENTS ONLY DESTINATION FARE BREAK POINTS MAY
                    BE CHANGED. REPRICE USING NORMAL/SPECIAL ONE WAY/ROUND
                    TRIP FARES/ANY RULE/FARE CLASS/RBD. PUBLIC FARES ARE
                    USED IF TICKETED FARE IS IN PUBLIC TARIFF. QUALIFIED
                    PRIVATE FARES OR PUBLIC FARES ARE USED IF TICKETED FARE
                    IS IN PRIVATE TARIFF. NEW FARE FOR FULLY FLOWN FARE
                    COMPONENTS MUST BE EQUAL TO OR HIGHER THAN TICKETED
                    FARE.
                    FOR TICKETING ON/AFTER 01MAR 21
                    REFUND REQUEST REQUIRED 24 HOURS BEFORE ORIGINALLY
                    SCHEDULED FLIGHT OF FIRST UNUSED TICKET COUPON.
                    CHARGE BDT 1500 PER PRICING UNIT. IF ALL PENALTIES IN
                    PRICING UNIT ARE PER PRICING UNIT COLLECT HIGHEST. IF
                    MIX OF PER FARE COMPONENT AND PER PRICING UNIT
                    CALCULATE EACH AS PER PRICING UNIT AND COLLECT HIGHEST.
                    DISCOUNT APPLIES TO CHILD/INFANT.
                    REFUND REQUEST MUST BE WITHIN 6 MONTHS AFTER TICKET
                    ISSUANCE. FORM OF REFUND - ORIGINAL FORM OF PAYMENT.
                    ONLY VALIDATING CARRIER MAY REFUND TICKET.
                    REPRICE FLOWN PORTION USING FARES IN EFFECT ON TICKET
                    ISSUANCE DATE. FOR FULLY FLOWN FARE COMPONENTS FARE
                    BREAK POINTS MAY NOT BE CHANGED. FOR PARTIALLY FLOWN
                    FARE COMPONENTS ONLY DESTINATION FARE BREAK POINTS MAY
                    BE CHANGED. REPRICE USING NORMAL/SPECIAL ONE WAY/ROUND
                    TRIP FARES/ANY RULE/FARE CLASS/RBD. PUBLIC FARES ARE
                    USED IF TICKETED FARE IS IN PUBLIC TARIFF. QUALIFIED
                    PRIVATE FARES OR PUBLIC FARES ARE USED IF TICKETED FARE
                    IS IN PRIVATE TARIFF. NEW FARE FOR FULLY FLOWN FARE
                    COMPONENTS MUST BE EQUAL TO OR HIGHER THAN TICKETED
                    FARE.
                    FOR TICKETING ON/AFTER 01APR 20
                    REFUND REQUEST REQUIRED BEFORE ORIGINALLY SCHEDULED
                    FLIGHT OF FIRST UNUSED TICKET COUPON.
                    CHARGE BDT 2000 PER PRICING UNIT. IF ALL PENALTIES IN
                    PRICING UNIT ARE PER PRICING UNIT COLLECT HIGHEST. IF
                    MIX OF PER FARE COMPONENT AND PER PRICING UNIT
                    CALCULATE EACH AS PER PRICING UNIT AND COLLECT HIGHEST.
                    DISCOUNT APPLIES TO CHILD/INFANT.
                    REFUND REQUEST MUST BE WITHIN 6 MONTHS AFTER TICKET
                    ISSUANCE. FORM OF REFUND - ORIGINAL FORM OF PAYMENT.
                    ONLY VALIDATING CARRIER MAY REFUND TICKET.
                    REPRICE FLOWN PORTION USING FARES IN EFFECT ON TICKET
                    ISSUANCE DATE. FOR FULLY FLOWN FARE COMPONENTS FARE
                    BREAK POINTS MAY NOT BE CHANGED. FOR PARTIALLY FLOWN
                    FARE COMPONENTS ONLY DESTINATION FARE BREAK POINTS MAY
                    BE CHANGED. REPRICE USING NORMAL/SPECIAL ONE WAY/ROUND
                    TRIP FARES/ANY RULE/FARE CLASS/RBD. PUBLIC FARES ARE
                    USED IF TICKETED FARE IS IN PUBLIC TARIFF. QUALIFIED
                    PRIVATE FARES OR PUBLIC FARES ARE USED IF TICKETED FARE
                    IS IN PRIVATE TARIFF. NEW FARE FOR FULLY FLOWN FARE
                    COMPONENTS MUST BE EQUAL TO OR HIGHER THAN TICKETED
                    FARE.
                    OR -
                    REFUND REQUEST REQUIRED ANYTIME AFTER ORIGINALLY
                    SCHEDULED FLIGHT OF FIRST UNUSED TICKET COUPON.
                    CHARGE BDT 2000 PER PRICING UNIT. IF ALL PENALTIES
                    IN PRICING UNIT ARE PER PRICING UNIT COLLECT
                    HIGHEST. IF MIX OF PER FARE COMPONENT AND PER
                    PRICING UNIT CALCULATE EACH AS PER PRICING UNIT
                    AND COLLECT HIGHEST. DISCOUNT APPLIES TO CHILD/
                    INFANT.
                    REFUND REQUEST MUST BE WITHIN 6 MONTHS AFTER TICKET
                    ISSUANCE. FORM OF REFUND - ORIGINAL FORM OF
                    PAYMENT. ONLY VALIDATING CARRIER MAY REFUND
                    TICKET.
                    REPRICE FLOWN PORTION USING FARES IN EFFECT ON
                    TICKET ISSUANCE DATE. FOR FULLY FLOWN FARE
                    COMPONENTS FARE BREAK POINTS MAY NOT BE CHANGED.
                    FOR PARTIALLY FLOWN FARE COMPONENTS ONLY
                    DESTINATION FARE BREAK POINTS MAY BE CHANGED.
                    REPRICE USING NORMAL/SPECIAL ONE WAY/ROUND TRIP
                    FARES/ANY RULE/FARE CLASS/RBD. PUBLIC FARES ARE
                    USED IF TICKETED FARE IS IN PUBLIC TARIFF.
                    QUALIFIED PRIVATE FARES OR PUBLIC FARES ARE USED
                    IF TICKETED FARE IS IN PRIVATE TARIFF. NEW FARE
                    FOR FULLY FLOWN FARE COMPONENTS MUST BE EQUAL TO
                    OR HIGHER THAN TICKETED FARE.

                    Segment 2
                    VOLUNTARY CHANGES
                    DO A CATEGORY 31 SPECIFIC TEXT ENTRY TO VIEW CONTENTS
                    ALSO REFERENCE 16 PENALTIES - FOR ADDITIONAL CHANGE INFORMATION


                    VOLUNTARY REFUNDS
                    UNLESS OTHERWISE SPECIFIED
                    APPLIES IN THE CASE OF DEATH OF PASSENGER OR FAMILY
                    MEMBER.
                    NO CHARGE. IF ALL PENALTIES IN PRICING UNIT ARE PER
                    PRICING UNIT COLLECT HIGHEST. IF MIX OF PER FARE
                    COMPONENT AND PER PRICING UNIT CALCULATE EACH AS PER
                    PRICING UNIT AND COLLECT HIGHEST.
                    REFUND REQUEST MUST BE WITHIN 6 MONTHS AFTER TICKET
                    ISSUANCE. FORM OF REFUND - ORIGINAL FORM OF PAYMENT. ONLY
                    VALIDATING CARRIER MAY REFUND TICKET.
                    REPRICE FLOWN PORTION USING FARES IN EFFECT ON TICKET
                    ISSUANCE DATE. FOR FULLY FLOWN FARE COMPONENTS FARE BREAK
                    POINTS MAY NOT BE CHANGED. FOR PARTIALLY FLOWN FARE
                    COMPONENTS ONLY DESTINATION FARE BREAK POINTS MAY BE
                    CHANGED. REPRICE USING NORMAL/SPECIAL ONE WAY FARES/ANY
                    RULE/FARE CLASS/SAME RBD. PUBLIC FARES ARE USED IF
                    TICKETED FARE IS IN PUBLIC TARIFF. QUALIFIED PRIVATE
                    FARES OR PUBLIC FARES ARE USED IF TICKETED FARE IS IN
                    PRIVATE TARIFF. NEW FARE FOR FULLY FLOWN FARE COMPONENTS
                    MUST BE EQUAL TO OR HIGHER THAN TICKETED FARE.
                    FOR TICKETING ON/AFTER 01APR 20
                    VALID FOR INFANT WITHOUT A SEAT.
                    NO CHARGE. IF ALL PENALTIES IN PRICING UNIT ARE PER
                    PRICING UNIT COLLECT HIGHEST. IF MIX OF PER FARE
                    COMPONENT AND PER PRICING UNIT CALCULATE EACH AS PER
                    PRICING UNIT AND COLLECT HIGHEST.
                    REFUND REQUEST MUST BE WITHIN 6 MONTHS AFTER TICKET
                    ISSUANCE. FORM OF REFUND - ORIGINAL FORM OF PAYMENT.
                    ONLY VALIDATING CARRIER MAY REFUND TICKET.
                    REPRICE FLOWN PORTION USING FARES IN EFFECT ON TICKET
                    ISSUANCE DATE. FOR FULLY FLOWN FARE COMPONENTS FARE
                    BREAK POINTS MAY NOT BE CHANGED. FOR PARTIALLY FLOWN
                    FARE COMPONENTS ONLY DESTINATION FARE BREAK POINTS MAY
                    BE CHANGED. REPRICE USING NORMAL/SPECIAL ONE WAY/ROUND
                    TRIP FARES/ANY RULE/FARE CLASS/RBD. PUBLIC FARES ARE
                    USED IF TICKETED FARE IS IN PUBLIC TARIFF. QUALIFIED
                    PRIVATE FARES OR PUBLIC FARES ARE USED IF TICKETED FARE
                    IS IN PRIVATE TARIFF. NEW FARE FOR FULLY FLOWN FARE
                    COMPONENTS MUST BE EQUAL TO OR HIGHER THAN TICKETED
                    FARE.
                    FOR TICKETING ON/AFTER 01MAR 21
                    REFUND REQUEST REQUIRED 24 HOURS BEFORE ORIGINALLY
                    SCHEDULED FLIGHT OF FIRST UNUSED TICKET COUPON.
                    CHARGE BDT 1500 PER PRICING UNIT. IF ALL PENALTIES IN
                    PRICING UNIT ARE PER PRICING UNIT COLLECT HIGHEST. IF
                    MIX OF PER FARE COMPONENT AND PER PRICING UNIT
                    CALCULATE EACH AS PER PRICING UNIT AND COLLECT HIGHEST.
                    DISCOUNT APPLIES TO CHILD/INFANT.
                    REFUND REQUEST MUST BE WITHIN 6 MONTHS AFTER TICKET
                    ISSUANCE. FORM OF REFUND - ORIGINAL FORM OF PAYMENT.
                    ONLY VALIDATING CARRIER MAY REFUND TICKET.
                    REPRICE FLOWN PORTION USING FARES IN EFFECT ON TICKET
                    ISSUANCE DATE. FOR FULLY FLOWN FARE COMPONENTS FARE
                    BREAK POINTS MAY NOT BE CHANGED. FOR PARTIALLY FLOWN
                    FARE COMPONENTS ONLY DESTINATION FARE BREAK POINTS MAY
                    BE CHANGED. REPRICE USING NORMAL/SPECIAL ONE WAY/ROUND
                    TRIP FARES/ANY RULE/FARE CLASS/RBD. PUBLIC FARES ARE
                    USED IF TICKETED FARE IS IN PUBLIC TARIFF. QUALIFIED
                    PRIVATE FARES OR PUBLIC FARES ARE USED IF TICKETED FARE
                    IS IN PRIVATE TARIFF. NEW FARE FOR FULLY FLOWN FARE
                    COMPONENTS MUST BE EQUAL TO OR HIGHER THAN TICKETED
                    FARE.
                    FOR TICKETING ON/AFTER 01APR 20
                    REFUND REQUEST REQUIRED BEFORE ORIGINALLY SCHEDULED
                    FLIGHT OF FIRST UNUSED TICKET COUPON.
                    CHARGE BDT 2000 PER PRICING UNIT. IF ALL PENALTIES IN
                    PRICING UNIT ARE PER PRICING UNIT COLLECT HIGHEST. IF
                    MIX OF PER FARE COMPONENT AND PER PRICING UNIT
                    CALCULATE EACH AS PER PRICING UNIT AND COLLECT HIGHEST.
                    DISCOUNT APPLIES TO CHILD/INFANT.
                    REFUND REQUEST MUST BE WITHIN 6 MONTHS AFTER TICKET
                    ISSUANCE. FORM OF REFUND - ORIGINAL FORM OF PAYMENT.
                    ONLY VALIDATING CARRIER MAY REFUND TICKET.
                    REPRICE FLOWN PORTION USING FARES IN EFFECT ON TICKET
                    ISSUANCE DATE. FOR FULLY FLOWN FARE COMPONENTS FARE
                    BREAK POINTS MAY NOT BE CHANGED. FOR PARTIALLY FLOWN
                    FARE COMPONENTS ONLY DESTINATION FARE BREAK POINTS MAY
                    BE CHANGED. REPRICE USING NORMAL/SPECIAL ONE WAY/ROUND
                    TRIP FARES/ANY RULE/FARE CLASS/RBD. PUBLIC FARES ARE
                    USED IF TICKETED FARE IS IN PUBLIC TARIFF. QUALIFIED
                    PRIVATE FARES OR PUBLIC FARES ARE USED IF TICKETED FARE
                    IS IN PRIVATE TARIFF. NEW FARE FOR FULLY FLOWN FARE
                    COMPONENTS MUST BE EQUAL TO OR HIGHER THAN TICKETED
                    FARE.
                    OR -
                    REFUND REQUEST REQUIRED ANYTIME AFTER ORIGINALLY
                    SCHEDULED FLIGHT OF FIRST UNUSED TICKET COUPON.
                    CHARGE BDT 2000 PER PRICING UNIT. IF ALL PENALTIES
                    IN PRICING UNIT ARE PER PRICING UNIT COLLECT
                    HIGHEST. IF MIX OF PER FARE COMPONENT AND PER
                    PRICING UNIT CALCULATE EACH AS PER PRICING UNIT
                    AND COLLECT HIGHEST. DISCOUNT APPLIES TO CHILD/
                    INFANT.
                    REFUND REQUEST MUST BE WITHIN 6 MONTHS AFTER TICKET
                    ISSUANCE. FORM OF REFUND - ORIGINAL FORM OF
                    PAYMENT. ONLY VALIDATING CARRIER MAY REFUND
                    TICKET.
                    REPRICE FLOWN PORTION USING FARES IN EFFECT ON
                    TICKET ISSUANCE DATE. FOR FULLY FLOWN FARE
                    COMPONENTS FARE BREAK POINTS MAY NOT BE CHANGED.
                    FOR PARTIALLY FLOWN FARE COMPONENTS ONLY
                    DESTINATION FARE BREAK POINTS MAY BE CHANGED.
                    REPRICE USING NORMAL/SPECIAL ONE WAY/ROUND TRIP
                    FARES/ANY RULE/FARE CLASS/RBD. PUBLIC FARES ARE
                    USED IF TICKETED FARE IS IN PUBLIC TARIFF.
                    QUALIFIED PRIVATE FARES OR PUBLIC FARES ARE USED
                    IF TICKETED FARE IS IN PRIVATE TARIFF. NEW FARE
                    FOR FULLY FLOWN FARE COMPONENTS MUST BE EQUAL TO
                    OR HIGHER THAN TICKETED FARE.


                    VOLUNTARY CHANGES
                    DO A CATEGORY 31 SPECIFIC TEXT ENTRY TO VIEW CONTENTS
                    ALSO REFERENCE 16 PENALTIES - FOR ADDITIONAL CHANGE INFORMATION


                    VOLUNTARY REFUNDS
                    UNLESS OTHERWISE SPECIFIED
                    APPLIES IN THE CASE OF DEATH OF PASSENGER OR FAMILY
                    MEMBER.
                    NO CHARGE. IF ALL PENALTIES IN PRICING UNIT ARE PER
                    PRICING UNIT COLLECT HIGHEST. IF MIX OF PER FARE
                    COMPONENT AND PER PRICING UNIT CALCULATE EACH AS PER
                    PRICING UNIT AND COLLECT HIGHEST.
                    REFUND REQUEST MUST BE WITHIN 6 MONTHS AFTER TICKET
                    ISSUANCE. FORM OF REFUND - ORIGINAL FORM OF PAYMENT. ONLY
                    VALIDATING CARRIER MAY REFUND TICKET.
                    REPRICE FLOWN PORTION USING FARES IN EFFECT ON TICKET
                    ISSUANCE DATE. FOR FULLY FLOWN FARE COMPONENTS FARE BREAK
                    POINTS MAY NOT BE CHANGED. FOR PARTIALLY FLOWN FARE
                    COMPONENTS ONLY DESTINATION FARE BREAK POINTS MAY BE
                    CHANGED. REPRICE USING NORMAL/SPECIAL ONE WAY FARES/ANY
                    RULE/FARE CLASS/SAME RBD. PUBLIC FARES ARE USED IF
                    TICKETED FARE IS IN PUBLIC TARIFF. QUALIFIED PRIVATE
                    FARES OR PUBLIC FARES ARE USED IF TICKETED FARE IS IN
                    PRIVATE TARIFF. NEW FARE FOR FULLY FLOWN FARE COMPONENTS
                    MUST BE EQUAL TO OR HIGHER THAN TICKETED FARE.
                    FOR TICKETING ON/AFTER 01APR 20
                    VALID FOR INFANT WITHOUT A SEAT.
                    NO CHARGE. IF ALL PENALTIES IN PRICING UNIT ARE PER
                    PRICING UNIT COLLECT HIGHEST. IF MIX OF PER FARE
                    COMPONENT AND PER PRICING UNIT CALCULATE EACH AS PER
                    PRICING UNIT AND COLLECT HIGHEST.
                    REFUND REQUEST MUST BE WITHIN 6 MONTHS AFTER TICKET
                    ISSUANCE. FORM OF REFUND - ORIGINAL FORM OF PAYMENT.
                    ONLY VALIDATING CARRIER MAY REFUND TICKET.
                    REPRICE FLOWN PORTION USING FARES IN EFFECT ON TICKET
                    ISSUANCE DATE. FOR FULLY FLOWN FARE COMPONENTS FARE
                    BREAK POINTS MAY NOT BE CHANGED. FOR PARTIALLY FLOWN
                    FARE COMPONENTS ONLY DESTINATION FARE BREAK POINTS MAY
                    BE CHANGED. REPRICE USING NORMAL/SPECIAL ONE WAY/ROUND
                    TRIP FARES/ANY RULE/FARE CLASS/RBD. PUBLIC FARES ARE
                    USED IF TICKETED FARE IS IN PUBLIC TARIFF. QUALIFIED
                    PRIVATE FARES OR PUBLIC FARES ARE USED IF TICKETED FARE
                    IS IN PRIVATE TARIFF. NEW FARE FOR FULLY FLOWN FARE
                    COMPONENTS MUST BE EQUAL TO OR HIGHER THAN TICKETED
                    FARE.
                    FOR TICKETING ON/AFTER 01MAR 21
                    REFUND REQUEST REQUIRED 24 HOURS BEFORE ORIGINALLY
                    SCHEDULED FLIGHT OF FIRST UNUSED TICKET COUPON.
                    CHARGE BDT 1500 PER PRICING UNIT. IF ALL PENALTIES IN
                    PRICING UNIT ARE PER PRICING UNIT COLLECT HIGHEST. IF
                    MIX OF PER FARE COMPONENT AND PER PRICING UNIT
                    CALCULATE EACH AS PER PRICING UNIT AND COLLECT HIGHEST.
                    DISCOUNT APPLIES TO CHILD/INFANT.
                    REFUND REQUEST MUST BE WITHIN 6 MONTHS AFTER TICKET
                    ISSUANCE. FORM OF REFUND - ORIGINAL FORM OF PAYMENT.
                    ONLY VALIDATING CARRIER MAY REFUND TICKET.
                    REPRICE FLOWN PORTION USING FARES IN EFFECT ON TICKET
                    ISSUANCE DATE. FOR FULLY FLOWN FARE COMPONENTS FARE
                    BREAK POINTS MAY NOT BE CHANGED. FOR PARTIALLY FLOWN
                    FARE COMPONENTS ONLY DESTINATION FARE BREAK POINTS MAY
                    BE CHANGED. REPRICE USING NORMAL/SPECIAL ONE WAY/ROUND
                    TRIP FARES/ANY RULE/FARE CLASS/RBD. PUBLIC FARES ARE
                    USED IF TICKETED FARE IS IN PUBLIC TARIFF. QUALIFIED
                    PRIVATE FARES OR PUBLIC FARES ARE USED IF TICKETED FARE
                    IS IN PRIVATE TARIFF. NEW FARE FOR FULLY FLOWN FARE
                    COMPONENTS MUST BE EQUAL TO OR HIGHER THAN TICKETED
                    FARE.
                    FOR TICKETING ON/AFTER 01APR 20
                    REFUND REQUEST REQUIRED BEFORE ORIGINALLY SCHEDULED
                    FLIGHT OF FIRST UNUSED TICKET COUPON.
                    CHARGE BDT 2000 PER PRICING UNIT. IF ALL PENALTIES IN
                    PRICING UNIT ARE PER PRICING UNIT COLLECT HIGHEST. IF
                    MIX OF PER FARE COMPONENT AND PER PRICING UNIT
                    CALCULATE EACH AS PER PRICING UNIT AND COLLECT HIGHEST.
                    DISCOUNT APPLIES TO CHILD/INFANT.
                    REFUND REQUEST MUST BE WITHIN 6 MONTHS AFTER TICKET
                    ISSUANCE. FORM OF REFUND - ORIGINAL FORM OF PAYMENT.
                    ONLY VALIDATING CARRIER MAY REFUND TICKET.
                    REPRICE FLOWN PORTION USING FARES IN EFFECT ON TICKET
                    ISSUANCE DATE. FOR FULLY FLOWN FARE COMPONENTS FARE
                    BREAK POINTS MAY NOT BE CHANGED. FOR PARTIALLY FLOWN
                    FARE COMPONENTS ONLY DESTINATION FARE BREAK POINTS MAY
                    BE CHANGED. REPRICE USING NORMAL/SPECIAL ONE WAY/ROUND
                    TRIP FARES/ANY RULE/FARE CLASS/RBD. PUBLIC FARES ARE
                    USED IF TICKETED FARE IS IN PUBLIC TARIFF. QUALIFIED
                    PRIVATE FARES OR PUBLIC FARES ARE USED IF TICKETED FARE
                    IS IN PRIVATE TARIFF. NEW FARE FOR FULLY FLOWN FARE
                    COMPONENTS MUST BE EQUAL TO OR HIGHER THAN TICKETED
                    FARE.
                    OR -
                    REFUND REQUEST REQUIRED ANYTIME AFTER ORIGINALLY
                    SCHEDULED FLIGHT OF FIRST UNUSED TICKET COUPON.
                    CHARGE BDT 2000 PER PRICING UNIT. IF ALL PENALTIES
                    IN PRICING UNIT ARE PER PRICING UNIT COLLECT
                    HIGHEST. IF MIX OF PER FARE COMPONENT AND PER
                    PRICING UNIT CALCULATE EACH AS PER PRICING UNIT
                    AND COLLECT HIGHEST. DISCOUNT APPLIES TO CHILD/
                    INFANT.
                    REFUND REQUEST MUST BE WITHIN 6 MONTHS AFTER TICKET
                    ISSUANCE. FORM OF REFUND - ORIGINAL FORM OF
                    PAYMENT. ONLY VALIDATING CARRIER MAY REFUND
                    TICKET.
                    REPRICE FLOWN PORTION USING FARES IN EFFECT ON
                    TICKET ISSUANCE DATE. FOR FULLY FLOWN FARE
                    COMPONENTS FARE BREAK POINTS MAY NOT BE CHANGED.
                    FOR PARTIALLY FLOWN FARE COMPONENTS ONLY
                    DESTINATION FARE BREAK POINTS MAY BE CHANGED.
                    REPRICE USING NORMAL/SPECIAL ONE WAY/ROUND TRIP
                    FARES/ANY RULE/FARE CLASS/RBD. PUBLIC FARES ARE
                    USED IF TICKETED FARE IS IN PUBLIC TARIFF.
                    QUALIFIED PRIVATE FARES OR PUBLIC FARES ARE USED
                    IF TICKETED FARE IS IN PRIVATE TARIFF. NEW FARE
                    FOR FULLY FLOWN FARE COMPONENTS MUST BE EQUAL TO
                    OR HIGHER THAN TICKETED FARE.</p>
            </div>
            <div className=' bg-[#ffedd1] text-[11px] p-2 rounded mt-5'>
                <p><span className=' font-medium'>*Important:</span> The airline fees are continuously changing. Flight Expert doesn’t certify the fees/price shown above. The mentioned fees are for prediction of easiness of our customer. You can change the date only by choosing the same airline on a different date. Users have to pay the fare difference of RBD or classes between booked and latest booking, if there is any.</p>
            </div>
        </div>
    )
}

export default FlightRules